//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Europa.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulo
    {
        public Modulo()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int IdModulo { get; set; }
        public string Icone { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
