//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Europa.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Modulo = new HashSet<Modulo>();
        }
    
        public int IdUsuario { get; set; }
        public string Nome { get; set; }
        public Nullable<int> CPF { get; set; }
        public string Email { get; set; }
        public string Foto { get; set; }
        public Nullable<int> QtdAcesso { get; set; }
        public Nullable<System.DateTime> DataNasc { get; set; }
        public Nullable<int> UltimoAcesso { get; set; }
        public Nullable<bool> FlagAdmin { get; set; }
        public string Sexo { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Telefone { get; set; }
        public string Senha { get; set; }
    
        public virtual ICollection<Modulo> Modulo { get; set; }
    }
}
